name: Run main script

on:
  workflow_dispatch:

  schedule:
    - cron: '5 0 * * 2-6'

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar main script
        run: python ./src/main.py


      - name: Enviar correo
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL }}
          password: ${{ secrets.PASS }}
          subject: "Github Actions - Ofertas de Trabajo Filtradas"
          html_body: file://data/email_body.html
          from: "GitHub Actions <${{ secrets.MAIL }}>"
          to: ${{ secrets.MAIL }}

      - name: Hacer commit y push de archivos generados
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Nuevos resultados con GitHub Actions
          branch: main
          commit_user_name: Franco Mariño [Actions]
          commit_user_email: ${{ secrets.MAIL }}
          commit_author: fmarinoa <${{ secrets.MAIL }}>